sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
      
install:
  - npm install

script:
  # - npm run travix neko .
  - npm run travix node
  # - npm run travix php .

env:
  - secure: "MamnIjFbl+sRoiwwiy3dcCSX1RuGPh2E1O7YeMIYfr0/MCogWQ2Boeg+Y0R+DCA3+MkfNWqWQzfdECpMVOByyYjWmkVbGZVcORI8Bdz+ICiFUTLdGZ3L3HqRBvtqn0wrFLwDeIGhjlfk+tmUcNDfv+L4ao6flrJ6wy+/GbL4kLQ="
